src/ralph/security/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from dj.choices import Choices
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ralph.assets.models.base import BaseObject
from ralph.lib.mixins.models import (
    AdminAbsoluteUrlMixin,
    TaggableMixin,
    TimeStampMixin
)
from ralph.lib.permissions import PermByFieldMixin


def any_exceeded(vulnerabilties):
    return any([v.is_deadline_exceeded for v in vulnerabilties])


class ScanStatus(Choices):
    _ = Choices.Choice

    ok = _("ok")
    fail = _("fail")
    error = _("error")


class Risk(Choices):
    _ = Choices.Choice

    low = _("low")
    medium = _("medium")
    high = _("high")


class Vulnerability(
    AdminAbsoluteUrlMixin,
    PermByFieldMixin,
    TimeStampMixin,
    TaggableMixin,
    models.Model,
):
    _allow_in_dashboard = True

    name = models.CharField(
        verbose_name=_("name"),
        max_length=1024,
        unique=False
    )
    display_name = models.CharField(
        verbose_name=_("display name"),
        max_length=1024
    )
    patch_deadline = models.DateTimeField(null=True, blank=True)
    risk = models.PositiveIntegerField(choices=Risk(), null=True, blank=True)
    external_vulnerability_id = models.IntegerField(
        unique=True,  # id means id
        null=True,
        blank=True,
        help_text=_('Id of vulnerability from external system'),
    )

    @property
    def is_deadline_exceeded(self):
        return self.patch_deadline < datetime.now()

    def __str__(self):
        deadline = (
            self.patch_deadline.strftime('%Y-%m-%d') if
            self.patch_deadline else '-'
        )
        return "{} ({})".format(self.name, deadline)


class SecurityScan(
    AdminAbsoluteUrlMixin,
    PermByFieldMixin,
    TimeStampMixin,
    TaggableMixin,
    models.Model,
):
    _allow_in_dashboard = True

    last_scan_date = models.DateTimeField()
    scan_status = models.PositiveIntegerField(choices=ScanStatus())
    next_scan_date = models.DateTimeField()
    details_url = models.URLField(max_length=255, blank=True)
    rescan_url = models.URLField(blank=True, verbose_name=_('Rescan url'))
    base_object = models.OneToOneField(
        BaseObject,
        on_delete=models.CASCADE,
    )
    vulnerabilities = models.ManyToManyField(Vulnerability, blank=True)
    # this is a quirk field, it is updated manually (for now it's in API)
    # this is because it's hard to handling it automatically
    # (its value is computated depending on M2M field and M2M signals are
    # complicated)
    is_patched = models.BooleanField(default=False)

    @property
    def is_ok(self):
        return self.scan_status == ScanStatus.ok.id

    def update_is_patched(self):
        """Updates `is_patched` field depending on vulnerabilities"""
        self.is_patched = not any_exceeded(self.vulnerabilities.all())

    def __str__(self):
        return "{} {} ({})".format(
            self.last_scan_date.strftime('%Y-%m-%d'),
            ScanStatus.from_id(self.scan_status).desc,
            self.base_object.content_type,
        )

src/ralph/security/__init__.py
default_app_config = 'ralph.security.apps.SecurityConfig'

src/ralph/security/views.py
# -*- coding: utf-8 -*-
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import NoReverseMatch
from django.utils.lru_cache import lru_cache
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from ralph.admin import RalphAdmin, RalphTabularInline, register
from ralph.admin.helpers import get_admin_url
from ralph.admin.sites import ralph_site
from ralph.admin.views.extra import RalphDetailView
from ralph.security.models import SecurityScan, Vulnerability


logger = logging.getLogger(__name__)


@lru_cache()
def _url_name_for_change_view(obj_class, view_name):
    """
    Returns `url_name` attribute of view named by `view_name` or None

    Takes registred ModelAdmin for `obj_class` and searches its `change_views`
    for view with name `view_name`.  Then returns `url_name` for found view.
    """
    if obj_class not in ralph_site._registry:
        return None
    model_admin = ralph_site._registry[obj_class]
    found_view = None
    for change_view in getattr(model_admin, 'change_views', []):
        if getattr(change_view, 'name', '') == view_name:
            found_view = change_view
            break
    return getattr(found_view, 'url_name', None)


def _linkify(to_linkify, url):
    return "<a href=\"{}\">{}</a>".format(url, to_linkify)


class ScanStatusMixin(object):
    field_name = _('Security scan')

    def _to_span(self, css, text):
        return'<span class="{}">{}</span>'.format(css, text)

    def scan_status(self, obj):
        try:
            scan = obj.securityscan
        except ObjectDoesNotExist:
            html = self._to_span('', 'No scan')
        else:
            if scan.is_ok:
                if not scan.is_patched:
                    html = self._to_span("alert", "Vulnerable")
                else:
                    html = self._to_span("success", "Host clean")
            else:
                html = self._to_span("warning", "Scan failed")

            url_name = _url_name_for_change_view(type(obj), 'security_info')
            if not url_name:
                logger.error("No security view for obj of type: %s", type(obj))
            else:
                try:
                    url = get_admin_url(obj, url_name)
                    html = _linkify(html, url)
                except NoReverseMatch:
                    logger.error("cant reverse url for: %s, %s", obj, url_name)
        return mark_safe(html)


class ScanStatusInChangeListMixin(ScanStatusMixin):
    def __init__(self, *args, **kwargs):
        self.scan_status.__func__.short_description = self.field_name

        super().__init__(*args, **kwargs)
        self.list_select_related += ['securityscan', ]


class ScanStatusInTableMixin(ScanStatusMixin):
    def __init__(self, *args, **kwargs):
        self.scan_status.__func__.title = self.field_name
        super().__init__(*args, **kwargs)


@register(Vulnerability)
class VulnerabilityAdmin(RalphAdmin):
    search_fields = ['name', ]


class VulnerabilitiesInline(RalphTabularInline):
    verbose_name = "Vulnerability"
    verbose_name_plural = "Vulnerabilities"
    model = SecurityScan.vulnerabilities.through
    raw_id_fields = ('vulnerability',)


@register(SecurityScan)
class SecurityScan(RalphAdmin):
    fields = (
        'last_scan_date', 'scan_status', 'next_scan_date', 'details_url',
        'rescan_url',
    )
    list_select_related = (
        'base_object', 'base_object__content_type',
    )

    inlines = [
        VulnerabilitiesInline,
    ]


class SecurityInfo(RalphDetailView):

    icon = 'lock'
    label = 'Security Info'
    name = 'security_info'
    url_name = None
    template_name = 'security/securityinfo/security_info.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            scan = self.object.securityscan
        except ObjectDoesNotExist:
            scan = None
        context['security_scan'] = scan
        return context

src/ralph/security/templates/security/securityinfo/security_info.html
{% extends BASE_TEMPLATE %}
{% load i18n %}

{% block bodyclass %}security-tab{% endblock%}

{% block view_content %}


<h1>{% trans "Security scan" %}</h1>
  {% if security_scan %}
    <table>
      <tr>
        <td>{% trans "last scan date" %}</td>
        <td>{{ security_scan.last_scan_date|date:"o-m-d" }}</td>
      </tr>
      <tr>
        <td>{% trans "scan status" %}</td>
        <td>{{ security_scan.get_scan_status_display }}</td>
      </tr>
      <tr>
        <td>{% trans "next scan date" %}</td>
        <td>{{ security_scan.next_scan_date|date:"o-m-d" }}</td>
      </tr>
      <tr>
        <td>{% trans "details" %}</td>
        <td><a href='{{ security_scan.details_url }}'>{{ security_scan.details_url|default:"-"}}</a></td>
      </tr>
      <tr>
        <td>{% trans "request for a scan" %}</td>
        <td><a href='{{ security_scan.rescan_url }}'>{{ security_scan.rescan_url|default:"-"}}</a></td>
      </tr>
    </table>

    <h3>{% trans "Vulnerabilities" %}</h3>
    {% if security_scan.vulnerabilities.all %}
      <table>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Risk" %}</th>
          <th>{% trans "Patch deadline" %}</th>
        </tr>
      {% for v in security_scan.vulnerabilities.all %}
        <tr>
          <td>{{ v.name }}</td>
          <td>{{ v.get_risk_display|default:"-" }}</td>
          <td
            {% if v.is_deadline_exceeded %}
              class='exceeded_deadline'
            {% endif %}
          >
            {{ v.patch_deadline|date:"o-m-d"|default:"-" }}
          </td>
        </tr>
      {% endfor %}
      </table>
    {% else %}
      <p>{% trans "No vulnerabilities found for this scan" %}</p>
    {% endif %}

  {% else %}
    <p>{% trans "No scan so far" %}</p>
  {% endif %}


{% endblock %}